<?php
$productData = $this->getProductData();
?>
<div class="product-grid">
    <?php foreach ($productData->getData() as $product) { ?>
        <div class="product-item">
            <?php $image = $product->getImageLink(); ?>
            <img src="<?php echo Mage::getBaseUrl("media/product/$image") ?>">
            <div class="product-details">
                <div class="product-info">
                    <div class="product-sku">
                        <?php echo $product->getSku(); ?>
                    </div>
                    <div class="product-name">
                        <?php echo $product->getName(); ?>
                    </div>
                    <div class="product-color">
                        <?php echo $product->getColor(); ?>
                    </div>
                    <div class="product-size">
                        <?php echo $product->getSize(); ?>
                    </div>
                </div>
                <div class="product-description">
                    <?php echo $product->getDescription(); ?>
                </div>
                <div class="product-price">
                    <?php echo $product->getPrice(); ?>
                </div>
                <div class="product-status">
                    <?php echo $product->getStatus(); ?>
                </div>
                <a href="<?php echo Mage::getBaseUrl('catalog/product/view?id=' . $product->getProductId()) ?>"
                    class="view-product">View Product</a>
            </div>
        </div>
    <?php } ?>
</div>