<?php
$categoryCollection = Mage::getModel("catalog/category")->getCollection();
?>
<div class="table" style="margin-top:20px;">
    <table border="1px solid black">
        <tr>
            <th>Category Name</th>
            <th>Category Status</th>
        </tr>
        <?php
        foreach ($categoryCollection->getData() as $category) { ?>
            <tr>
                <td>
                    <?php print_r($category->getCategoryName());
                    ?>
                </td>
                <td>
                    <?php print_r($category->getMappedStatus()); ?>
                </td>
                <td>
                <td>
                    <a
                        href="http://localhost/Practice/mvc/admin/catalog_category/form?id=<?php echo $category->getCategoryId(); ?>">Edit</a>
                </td>
                <td>
                    <a
                        href="http://localhost/Practice/mvc/admin/catalog_category/delete?id=<?php echo $category->getCategoryId(); ?>">Delete</a>
                </td>

            </tr>

        <?php } ?>
    </table>
</div>