<div class="header">
    <ul>
        <li> <img src="<?php echo Mage::getBaseUrl('skin/images/1.png'); ?>" class="logo"></li>
        <li><a href='<?php echo Mage::getBaseUrl('') ?>'>Home</a></li>
        <li><a href='<?php echo Mage::getBaseUrl('admin/user/login') ?>'>Admin Login</a></li>
        <li><a href='<?php echo Mage::getBaseUrl('customer/account/login') ?>'>Customer Login</a></li>
        <li><a href='<?php echo Mage::getBaseUrl('cart/index/index') ?>'>View Cart</a></li>
        <li><a href='<?php echo Mage::getBaseUrl('catalog/category/view') ?>'>Add Product</a></li>
        <li><a href='<?php echo Mage::getBaseUrl('cart/index/list') ?>'>My Orders</a></li>
    </ul>
</div>