<!-- <div class="header">
    <ul>
        <li> <img src="<?php echo Mage::getBaseUrl('skin/images/1.png'); ?>" class="logo"></li>
        <li><a href='<?php echo Mage::getBaseUrl('customer/account/login') ?>'>Customer Login</a></li>
        <li><a href='<?php echo Mage::getBaseUrl('admin/catalog_product/form') ?>'>Product Form</a></li>
        <li><a href='<?php echo Mage::getBaseUrl('admin/catalog_category/form') ?>'>Category Form</a></li>
        <li><a href='<?php echo Mage::getBaseUrl('admin/catalog_product/list') ?>'>Product List</a></li>
        <li><a href='<?php echo Mage::getBaseUrl('admin/catalog_category/list') ?>'>Category List</a></li>
    </ul>
</div> -->
<div class="header">
    <ul>
        <li> <img src="<?php echo Mage::getBaseUrl('skin/images/1.png'); ?>" class="logo"></li>
        <li><a href='<?php echo Mage::getBaseUrl('customer/account/login') ?>'>Customer Login</a></li>
        <li><a href='<?php echo Mage::getBaseUrl('admin/user/login') ?>'>Admin Login</a></li>
        <li><a href='<?php echo Mage::getBaseUrl('admin/catalog_product/form') ?>'>Product Form</a></li>

    </ul>
</div>