<?php
$customer = $this->getCustomerDetails();
?>
<table class="table-new" border="1">
    <thead>
        <tr>
            <th>Customer Id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Details</th>
        </tr>
    </thead>
    <tr>
        <td>
            <?php echo $customer->getId(); ?>
        </td>
        <td>
            <?php echo $customer->getFirstName(); ?>
        </td>
        <td>
            <?php echo $customer->getLastName(); ?>
        </td>
        <td>
            <?php echo $customer->getCustomerEmail(); ?>

        </td>
    </tr>
</table>
<?php echo '<pre>';
$order = $this->getOrder();
print_r($order);
echo 'shippingId';
print_r($this->getShippingData($order->getShippingId()));
print_r($this->getPaymentData($order->getPaymentId()));
print_r($order->getPaymentId());
foreach ($this->getHistoryData($order->getId())->getData() as $item) {
    print_r($item);
}

foreach ($this->getOrderItems()->getData() as $item) {
    print_r($item);
    ?>
    <h3>Product Details</h3>
    <?php
    print_r($this->getProductData($item->getProductId()));
}


?>