<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product Details</title>

</head>

<body>

    <h2>Product Details</h2>

    <?php
    $productData = $this->getProductData();
    foreach ($productData->getData() as $product) {
        ?>

        <div class="product-details">
            <img src="<?php echo Mage::getBaseUrl("media/product/{$product->getImageLink()}") ?>" alt="Product Image">
            <table>
                <tr>
                    <th>Name</th>
                    <td>
                        <?php echo $product->getName(); ?>
                    </td>
                </tr>
                <tr>
                    <th>Price</th>
                    <td>
                        <?php echo $product->getPrice(); ?>$
                    </td>
                </tr>
                <tr>
                    <th>Color</th>
                    <td>
                        <?php echo $product->getColor(); ?>
                    </td>
                </tr>
                <tr>
                    <th>Description</th>
                    <td>
                        <?php echo $product->getDescription(); ?>
                    </td>
                </tr>
            </table>

            <form method="post" action="<?php echo Mage::getBaseUrl('sales/quote/add') ?>">
                <input type="hidden" name="productData[product_id]" value="<?php echo $product->getProductId(); ?>">
                <div class="row">
                    <label for="quantity">Enter Quantity</label>
                    <input type="text" name="productData[qty]">
                </div>
                <div class="row">
                    <input type="submit" value="Add To Cart" name="submit">
                    <input type="button" value="View Cart" name="viewCart"
                        onclick="window.location.href = '<?php echo Mage::getBaseUrl('cart/index/index') ?>';">
                </div>
            </form>
        </div>

    <?php } ?>

</body>

</html>