<?php
$bannerModel = $this->getBanner();
?>
<div class="form" style="border:1px solid black; width:30vw; padding: 15px">
    <h2>Image Upload Form</h2>
    <form action="<?php echo Mage::getBaseUrl('admin/banner/save') ?>" method="post" enctype="multipart/form-data">
        <div class="row">
            <input type="hidden" name="banner[banner_id]" value="<?php echo $bannerModel->getBannerId(); ?>">
        </div>
        <div class="row">
            <?php $image = $bannerModel->getBannerImage(); ?>
            <img src="<?php echo Mage::getBaseUrl("media/banner/$image") ?>" style="width:200px;">
        </div>
        <div class="row">
            <label for="image">Select Banner Image:</label>
            <input type="file" name="banner_image" id="image" accept="image/*"
                value="<?php echo $bannerModel->getBannerImage(); ?>">
        </div>
        <div class=" row">
            <label for="sku">Status : </label>
            <select id="status" name="banner[status]">
                <option value="1" <?php echo $bannerModel->getStatus() == 1 ? 'selected' : '' ?>>Enabled</option>
                <option value="0" <?php echo $bannerModel->getStatus() == 0 ? 'selected' : '' ?>>Disabled</option>
            </select>
        </div>

        <div class="row">
            <label for="status">Show On : </label>
            <select id="status" name="banner[show_on]">
                <option value="HomePage" <?php echo $bannerModel->getShowOn() == 'HomePage' ? 'selected' : '' ?>>Home
                    Page
                </option>
                <option value="CartPage" <?php echo $bannerModel->getShowOn() == 'CartPage' ? 'selected' : '' ?>>Cart
                    Page
                </option>
                <option value="SalePage" <?php echo $bannerModel->getShowOn() == 'SalePage' ? 'selected' : '' ?>>Sales
                    Page
                </option>
            </select>

        </div>
        <div class="row">
            <input type="submit" value="Submit" name="submit">
        </div>
    </form>
</div>