<?php
echo $this->getRequest()->getParams('pid');
$productModel = Mage::getModel('catalog/product')->load(2);
// echo '<pre>';
print_r($productModel->getId());
print_r($productModel->getPname());
print_r($productModel->getPtype());
print_r($productModel->getcategory());
print_r($productModel->getShipping_cost());
echo "<br>";
// print_r($productModel);
echo $this->getChildHtml('');
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

</body>

</html>