<!DOCTYPE html>
<html lang="en">

<head>
    <title>1column</title> <?php echo $this->getChildHtml('head') ?>
</head>

<body>
    <div>
        <?php echo $this->getChildHtml('header') ?>
    </div>
    <div>
        <?php echo $this->getChildHtml('content') ?>
    </div>
    <div>
        <?php echo $this->getChildHtml('footer') ?>
    </div>

    <div>
        <?php echo $this->getChildHtml('messages') ?>
    </div>

    <?php echo $this->getRequest()->getParams('pid'); ?>
    <?php echo $this->getRequest()->getParams('name'); ?>
</body>

</html>