<?php
$ProductModel = $this->getProduct();
?>
<div class="form" style="border:1px solid black; width:30vw; padding: 15px">
    <h2>Product Form</h2>
    <form method="POST" action="<?php echo $this->getUrl('admin/catalog_product/save') ?>">
        <div class="row">
            <input type="hidden" name="catalog_product[product_id]"
                value="<?php echo $ProductModel->getProductId(); ?>">
        </div>
        <div class="row">
            <label for="sku">SKU : </label>
            <input type="text" name="catalog_product[sku]" id="sku" value="<?php echo $ProductModel->getSku(); ?>">
        </div>
        <div class="row">
            <label for="name">Name : </label>
            <input type="text" name="catalog_product[name]" id="name" value="<?php echo $ProductModel->getName(); ?>">
        </div>

        <div class="row">
            <label for="color">Color : </label>
            <input type="text" name="catalog_product[color]" id="color"
                value="<?php echo $ProductModel->getColor(); ?>">
        </div>

        <div class="row">
            <label for="size">Size : </label>
            <input type="text" name="catalog_product[size]" id="size" value="<?php echo $ProductModel->getSize(); ?>">
        </div>

        <div class="row">
            <label for="description">Description :
                <textarea name="catalog_product[description]" id="description" cols="30"
                    rows="10"><?php echo $ProductModel->getDescription() ?></textarea>
                <value>
            </label>
        </div>

        <div class="row">
            <label for="image_link">Image Link : </label>
            <input type="file" name="catalog_product[image_link]" id="image_link"
                value="<?php echo $ProductModel->getImageLink(); ?>">
        </div>

        <div class="row">
            <label for="link">Link : </label>
            <input type="file" name="catalog_product[link]" id="link" value="<?php echo $ProductModel->getLink(); ?>">
        </div>
        <?php $categoryList = $this->getCategoryList();?>
        <div class="row">
            <label for="category_id">Category:</label>
            <select name="product[category_id]">
                <?php foreach ($categoryList->getData() as $category): ?>
                    <option value="<?php echo $category->getCategoryId() ?>" <?php echo $category->getCategoryId() == $ProductModel->getCategoryId() ? 'selected' : ''; ?>>
                        <?php echo $category->getCategoryName(); ?>
                    </option>
                <?php endforeach; ?>
            </select>

        </div>
        <div class="row">
            <label for="price">Price : </label>
            <input type="number" name="catalog_product[price]" id="price"
                value="<?php echo $ProductModel->getPrice(); ?>">
        </div>
        <div class="row">
            <label for="mfr_cost">Manufacture Cost</label>
            <input type="number" name="catalog_product[mfr_cost]" id="mfr_cost"
                value="<?php echo $ProductModel->getMfrCost(); ?>">
        </div>
        <div class="row">
            <label for="shipping_cost">Shipping Cost</label>
            <input type="number" name="catalog_product[shipping_cost]" id="shipping_cost"
                value="<?php echo $ProductModel->getShippingCost(); ?>">
        </div>
        <div class="row">
            <label for="total_cost">Total Cost</label>
            <input type="number" name="catalog_product[total_cost]" id="total_cost"
                value="<?php echo $ProductModel->getTotalCost(); ?>">
        </div>
        <div class="row">
            <label for="margin_percentage">Margin Percentage : </label>
            <input type="number" name="catalog_product[margin_percentage]" id="margin_percentage"
                value="<?php echo $ProductModel->getMarginPercentage(); ?>">
        </div>
        <div class="row">
            <label for="min_price">Min Price : </label>
            <input type="number" name="catalog_product[min_price]" id="min_price"
                value="<?php echo $ProductModel->getMinPrice(); ?>">
        </div>
        <div class="row">
            <label for="status">Status : </label>
            <select id="status" name="catalog_product[status]">
                <option value="1" <?php echo $ProductModel->getStatus() == 'Enabled' ? 'selected' : '' ?>>Enabled</option>
                <option value="0" <?php echo $ProductModel->getStatus() == 'Disabled' ? 'selected' : '' ?>>Disabled</option>
            </select>
        </div>
        <div class="row">
            <input type="submit" value="Submit">
        </div>
    </form>
</div>