<?php $addressData = $this->getAddressData()->getData();
$customerEmail = $this->getCustomerEmail();
?>
<section class="checkout-section">
    <div class="item-section">
        <h2>Items</h2>
        <div class="quote-item">
            <?php
            $items = $this->getQuoteItems(); ?>
            <h2>Items</h2>
            <?php foreach ($items->getData() as $item) { ?>
                <div class="quote-items">
                    <label>Item Id :</label>
                    <?php echo $item->getItemId(); ?>
                </div>
                <div class="quote-items">
                    <label>Product Id :</label>
                    <?php echo $item->getProductId(); ?>
                </div>
                <div class="quote-items">
                    <label>Price :</label>
                    <?php echo $item->getPrice(); ?>
                </div>
                <div class="quote-items">
                    <label>Qty :</label>
                    <?php echo $item->getQty(); ?>
                </div>
                <div class="quote-items">
                    <label>Row Total :</label>
                    <?php echo $item->getRowTotal(); ?>
                </div>

            <?php } ?>
        </div>
    </div>
    <div class="first">
        <div class="billingAddress">
            <h2>Billing Address</h2>
            <hr>
        </div>
        <?php if (!empty ($addressData)): ?>
            <?php foreach ($addressData as $addValue) { ?>
                <div class="addressBoxes">
                    <div id="asdasdasdasd" class="address-cards"
                        data-json='{"billing_address":"<?php echo $addValue->getBillingAddress(); ?>","billing_city":"<?php echo $addValue->getBillingCity(); ?>","billing_region":"<?php echo $addValue->getBillingRegion(); ?>","billing_country":"<?php echo $addValue->getBillingCountry(); ?>","billing_phone":"<?php echo $addValue->getBillingPhone(); ?>"}'>
                        <p>Address :
                            <?php echo $addValue->getBillingAddress() ?>
                        </p>
                        <p>City :
                            <?php echo $addValue->getBillingCity() ?>
                        </p>
                        <p>Region :
                            <?php echo $addValue->getBillingRegion() ?>
                        </p>
                        <p>Country :
                            <?php echo $addValue->getBillingCountry() ?>
                        </p>
                        <p>Phone No:
                            <?php echo $addValue->getBillingPhone() ?>
                        </p>
                    </div>
                </div>
            <?php }
            ?>
        <?php endif; ?>
    </div>
    <div class="form-section">
        <form action="<?php echo Mage::getBaseUrl('sales/quote/convert') ?>" method="post" class="sales-quote-form">
            <h2>Customer Information</h2>
            <div class="form-group">

                <!-- Billing Information -->
                <label>Email :</label>
                <div class="field-group">
                    <input type="text" id="email" name="sales_quote_customer[email]"
                        value="<?php echo $customerEmail; ?>" class="input-billing-address">
                </div>
                <div class="field-group">
                    <label for="billing_address" class="label-billing-address">Billing Address:</label>
                    <input type="text" id="billing_address" name="sales_quote_customer[billing_address]"
                        class="input-billing-address">
                </div>
                <div class="field-group">
                    <label for="billing_city" class="label-billing-city">Billing City:</label>
                    <input type="text" id="billing_city" name="sales_quote_customer[billing_city]"
                        class="input-billing-city">
                </div>

                <div class="field-group">
                    <label for="billing_region" class="label-billing-region">Billing Region:</label>
                    <input type="text" id="billing_region" name="sales_quote_customer[billing_region]"
                        class="input-billing-region">
                </div>

                <div class="field-group">
                    <label for="billing_country" class="label-billing-country">Billing Country:</label>
                    <input type="text" id="billing_country" name="sales_quote_customer[billing_country]"
                        class="input-billing-country">
                </div>

                <div class="field-group">
                    <label for="billing_phone" class="label-billing-phone">Billing Phone:</label>
                    <input type="tel" id="billing_phone" name="sales_quote_customer[billing_phone]"
                        class="input-billing-phone">
                </div>

                <div class="field-group">
                    <label for="billing_post_code" class="label-billing-post_code">Billing Post Code:</label>
                    <input type="text" id="billing_post_code" name="sales_quote_customer[billing_post_code]"
                        class="input-billing-post_code">
                </div>

            </div>

            <h2>Shipping Details</h2>
            <div class="form-group">

                <!-- Shipping Information -->
                <input type="checkbox" id="same_as_billing" onchange="copyBillingToShipping()"
                    class="checkbox-same-as-billing">
                <label for="same_as_billing" class="label-same-as-billing">Same as Billing</label>

                <div class="field-group">
                    <label for="shipping_address" class="label-shipping-address">Shipping Address:</label>
                    <input type="text" id="shipping_address" name="sales_quote_customer[shipping_address]"
                        class="input-shipping-address">
                </div>

                <div class="field-group">
                    <label for="shipping_city" class="label-shipping-city">Shipping City:</label>
                    <input type="text" id="shipping_city" name="sales_quote_customer[shipping_city]"
                        class="input-shipping-city">
                </div>

                <div class="field-group">
                    <label for="shipping_region" class="label-shipping-region">Shipping Region:</label>
                    <input type="text" id="shipping_region" name="sales_quote_customer[shipping_region]"
                        class="input-shipping-region">
                </div>

                <div class="field-group">
                    <label for="shipping_country" class="label-shipping-country">Shipping Country:</label>
                    <input type="text" id="shipping_country" name="sales_quote_customer[shipping_country]"
                        class="input-shipping-country">
                </div>

                <div class="field-group">
                    <label for="shipping_phone" class="label-shipping-phone">Shipping Phone:</label>
                    <input type="tel" id="shipping_phone" name="sales_quote_customer[shipping_phone]"
                        class="input-shipping-phone">
                </div>

                <div class="field-group">
                    <label for="shipping_post_code" class="label-shipping-post_code">Shipping Post Code:</label>
                    <input type="text" id="shipping_post_code" name="sales_quote_customer[shipping_post_code]"
                        class="input-shipping-post_code">
                </div>

            </div>
            <!-- <input type="hidden" value="<?php echo $this->getQuoteId() ?>" name="sales_quote[quote_id]"> -->
            <h2>Shipping Method</h2>
            <div class="form-group">
                <div class="field-group">
                    <label for="shipping_options" class="label-shipping-options">Shipping Options:</label>
                    <select id="shipping_options" name="sales_quote_shipping_method[shipping_method]"
                        class="select-payment-options">
                        <?php $shippingOptions = $this->getShippingOption(); ?>
                        <?php foreach ($shippingOptions as $key => $value) { ?>
                            <option value="<?php echo $key ?>">
                                <?php echo $value ?>
                            </option>
                        <?php } ?>
                    </select>
                </div>
            </div>
            <div class="payment">
                <h2>Payment Options</h2>
                <div class="form-group">
                    <div class="field-group">
                        <label for="payment_options" class="label-payment-options">Payment Options:</label>
                        <select id="payment_options" name="sales_quote_payment_method[payment_method]"
                            class="select-payment-options">
                            <?php $paymentOptions = $this->getPaymentOption(); ?>
                            <?php foreach ($paymentOptions as $key => $value) { ?>
                                <option value="<?php echo $key ?>">
                                    <?php echo $value ?>
                                </option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
                <div class="form-group input-creditcard" id="creditcard-fields">
                    <label for="card_number">Card Number:</label>
                    <input type="text" id="card_number" name="sales_quote_payment_method[card_number]"
                        placeholder="Enter card number" required>
                </div>
            </div>
            <input type="submit" value="Place Order" class="submit-button">
        </form>
    </div>
</section>
<script>
    const paymentOptionsSelect = document.getElementById('payment_options');
    const creditCardFields = document.getElementById('creditcard-fields');

    paymentOptionsSelect.addEventListener('change', function () {
        const selectedOption = this.value;
        if (selectedOption === 'creditcard') {
            creditCardFields.style.display = 'block';
        } else {
            creditCardFields.style.display = 'none';
        }
    });
    creditCardFields.style.display = 'none';
</script>

<script>
    function copyBillingToShipping() {
        if (document.getElementById('same_as_billing').checked) {
            document.getElementById('shipping_address').value = document.getElementById('billing_address').value;
            document.getElementById('shipping_city').value = document.getElementById('billing_city').value;
            document.getElementById('shipping_region').value = document.getElementById('billing_region').value;
            document.getElementById('shipping_country').value = document.getElementById('billing_country').value;
            document.getElementById('shipping_phone').value = document.getElementById('billing_phone').value;
            document.getElementById('shipping_post_code').value = document.getElementById('billing_post_code').value;
            // document.getElementById('shipping_zip').value = document.getElementById('billing_zip').value;
        } else {
            // Clear shipping fields if checkbox is unchecked
            document.getElementById('shipping_address').value = '';
            document.getElementById('shipping_city').value = '';
            document.getElementById('shipping_region').value = '';
            document.getElementById('shipping_country').value = '';
            document.getElementById('shipping_phone').value = '';
            document.getElementById('shipping_post_code').value = '';
            // document.getElementById('shipping_zip').value = '';
        }
    }
</script>
<script type="text/javascript">
    $('.address-cards').each((i, e) => {
        console.log($(e).attr('data-json'))
        $(e).click(() => {
            var _data = JSON.parse($(e).attr('data-json'))
            for (var key in _data) {
                if (_data.hasOwnProperty(key)) {
                    $('#' + key).val(_data[key]);
                }
            }
        });
    })
</script>