<form method="post" action="<?php echo Mage::getBaseUrl('sales/quote/save') ?>">
    <div>
        <label for="email">Email:</label>
        <input type="text" id="email" name="seles_quote_customer[email]"><br>
    </div>
    <div>
        <label for="billing_address">Billing Address:</label>
        <input type="text" id="billing_address" name="seles_quote_customer[billing_address]"><br>
    </div>
    <div>
        <label for="billing_city">Billing City:</label>
        <input type="text" id="billing_city" name="seles_quote_customer[billing_city]"><br>
    </div>
    <div>
        <label for="billing_region">Billing Region:</label>
        <input type="text" id="billing_region" name="seles_quote_customer[billing_region]"><br>
    </div>
    <div>
        <label for="billing_country">Billing Country:</label>
        <input type="text" id="billing_country" name="seles_quote_customer[billing_country]"><br>
    </div>
    <div>
        <label for="billing_phone">Billing Phone:</label>
        <input type="tel" id="billing_phone" name="seles_quote_customer[billing_phone]"><br>
    </div>
    <div>
        <label for="shipping_address">Shipping Address:</label>
        <input type="text" id="shipping_address" name="seles_quote_customer[shipping_address]"><br>
    </div>
    <div>
        <label for="shipping_city">Shipping City:</label>
        <input type="text" id="shipping_city" name="seles_quote_customer[shipping_city]"><br>
    </div>
    <div>
        <label for="shipping_region">Shipping Region:</label>
        <input type="text" id="shipping_region" name="seles_quote_customer[shipping_region]"><br>
    </div>
    <div>
        <label for="shipping_country">Shipping Country:</label>
        <input type="text" id="shipping_country" name="seles_quote_customer[shipping_country]"><br>
    </div>
    <div>
        <label for="shipping_phone">Shipping Phone:</label>
        <input type="tel" id="shipping_phone" name="seles_quote_customer[shipping_phone]"><br>
    </div>
    <input type="submit" value="Submit">
</form>


checkout first check customer login
left side all product
right side billing and shipping,method(express,) addess third section payment(cod,call,credit card);


db
sales_quote_customer add post_code
sales_quote add shipping_method,payment_method,card_number,order_id