<?php
$quote = $this->getQuote();
foreach ($quote->getData() as $_quote) { ?>
    <div>
        <label>Quote Id :</label>
        <?php echo $_quote->getQuoteId(); ?>
    </div>
    <div>
        <label>Tax Percent :</label>
        <?php echo $_quote->getTaxPercent(); ?>
    </div>
    <div>
        <label>Grand Total :</label>
        <?php echo $_quote->getGrandTotal(); ?>
    </div>
    <div>
        <a href="<?php echo Mage::getBaseUrl('sales/order/add?id=') . $_quote->getQuoteId() ?>">Order</a>
    </div>
<?php }
$items = $this->getQuoteItems(); ?>
<h2>Items</h2>
<div class="quote-item">
    <?php foreach ($items->getData() as $item) { ?>
        <div class="quote-items">
            <label>Item Id :</label>
            <?php echo $item->getItemId(); ?>
        </div>
        <div class="quote-items">
            <label>Product Id :</label>
            <?php echo $item->getProductId(); ?>
        </div>
        <div class="quote-items">
            <label>Price :</label>
            <?php echo $item->getPrice(); ?>
        </div>
        <div class="quote-items">
            <label>Qty :</label>
            <?php echo $item->getQty(); ?>
        </div>
        <div class="quote-items">
            <label>Row Total :</label>
            <?php echo $item->getRowTotal(); ?>
        </div>
        <br>
        <div class="quote-item-actions">
            <a href="<?php echo Mage::getBaseUrl('sales/quote/delete?id=') . $item->getItemId() ?>">Delete</a>
            <a href="<?php echo Mage::getBaseUrl('sales/quote/update?id=') . $item->getItemId() ?>">Update</a>
        </div>
        <br>
    </div>
<?php } ?>