<?php
$quote = $this->getQuote();
foreach ($quote->getData() as $_quote) { ?>
    <div>
        <label>Quote Id :</label>
        <?php echo $_quote->getQuoteId(); ?>
    </div>
    <div>
        <label>Tax Percent :</label>
        <?php echo $_quote->getTaxPercent(); ?>
    </div>
    <div>
        <label>Grand Total :</label>
        <?php echo $_quote->getGrandTotal(); ?>
    </div>
<?php }
$items = $this->getQuoteItems(); ?>
<h2>Items</h2>
<?php foreach ($items->getData() as $item) { ?>
    <div>
        <label>Item Id :</label>
        <?php echo $item->getItemId(); ?>
    </div>
    <div>
        <label>Product Id :</label>
        <?php echo $item->getProductId(); ?>
    </div>
    <div>
        <label>Price :</label>
        <?php echo $item->getPrice(); ?>
    </div>
    <div>
        <label>Qty :</label>
        <?php echo $item->getQty(); ?>
    </div>
    <div>
        <label>Row Total :</label>
        <?php echo $item->getRowTotal(); ?>
    </div>
    <div>
        <a href="<?php echo Mage::getBaseUrl('sales/quote/delete?id=') . $item->getItemId() ?>">Delete</a>
        <a href="<?php echo Mage::getBaseUrl('sales/quote/update?id=') . $item->getItemId() ?>">Update</a>
    </div>
    <br>
<?php } ?>