<div class="header">
    <ul>
        <li> <img src="<?php echo Mage::getBaseUrl('skin/images/1.png'); ?>" class="logo"></li>
        <li><a href='<?php echo Mage::getBaseUrl('') ?>'>Home</a></li>
        <li><a href='<?php echo Mage::getBaseUrl('admin/user/login') ?>'>Admin Login</a></li>
        <li><a href='<?php echo Mage::getBaseUrl('admin/catalog_product/form') ?>'>Product Form</a></li>
        <li><a href='<?php echo Mage::getBaseUrl('admin/catalog_category/form') ?>'>Category Form</a></li>
        <li><a href='<?php echo Mage::getBaseUrl('admin/catalog_product/list') ?>'>Product List</a></li>
        <li><a href='<?php echo Mage::getBaseUrl('admin/catalog_category/list') ?>'>Category List</a></li>
        <li><a href='<?php echo Mage::getBaseUrl('admin/banner/form') ?>'>Banner Form</a></li>
        <li><a href='<?php echo Mage::getBaseUrl('admin/banner/list') ?>'>Banner List</a></li>
        <li><a href='<?php echo Mage::getBaseUrl('admin/user/logout') ?>'>Admin Logout</a></li>
    </ul>
</div>