<?php
$data=$this->getUserName();
?>
<form method="post" action="<?php echo Mage::getBaseUrl('admin/calculator/save') ?>">
    <input type="hidden" name="calculator[id]" value="<?php echo $data->getId();?>">
    <label>User Name :</label>
    <input type="text" name="calculator[user_name]" value="<?php echo $data->getUserName()?>">
    <label>Input Box 1:</label>
    <input type="number" name="calculator[from_number]" value="">
    <label>Operator</label>
    <select name="calculator[operator]">
        <option value="add">+</option>
        <option value="sub">-</option>
        <option value="mul">*</option>
        <option value="div">/</option>
    </select>
    <label>Input Box 2:</label>
    <input type="text" name="calculator[to_number]" value="">
    <input type="submit" value="Equal TO" name="submit">
 </from>